### ISSUE TITLE
Date field type is not implemented

### ISSUE THREAD

**Issue by danielfpedro** [Holt59/cakephp3-bootstrap3-helpers#16]
The Date field type is not implemented, theres any workaround about it?

**Comment by Holt59** [comment]
Check the latest commit, should correctly add `form-control` class to select inputs. Unfortunately, Bootstrap `inputs` do not work well with CakePHP Date field since they have a `width: 100%`. You need to add some CSS like:
```css
.form-group.date label {
    display: block;
}
.form-group.date select.form-control {
    width: 33%;
    display: inline-block;
}
```
Hope it'll help you!
